<?php

declare(strict_types=1);

use MWGuerra\WebTerminalStream\Security\HostKeyVerificationException;
use MWGuerra\WebTerminalStream\Security\SshHostKeyVerifier;

// A real ed25519 host key and its OpenSSH fingerprints (from `ssh-keygen -lf`).
const WTS_HOST_KEY = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN3+5ljw+B4IQLbmebVHtrrGv12iu4/ZPUZH5T/+yNB1 wts-test-host';
const WTS_SHA256 = 'SHA256:l1C7yZJ+mCVTwIunDQ0ZzytglTeg5SloW66Iwm874pc';
const WTS_MD5 = 'MD5:5d:92:06:34:aa:cb:93:8e:cd:cf:fd:28:01:cf:4d:d0';

beforeEach(function () {
    $this->verifier = new SshHostKeyVerifier;
});

describe('SshHostKeyVerifier', function () {
    it('computes OpenSSH-format fingerprints', function () {
        [$sha256, $md5] = $this->verifier->fingerprints(WTS_HOST_KEY);

        expect($sha256)->toBe(WTS_SHA256)
            ->and($md5)->toBe(WTS_MD5);
    });

    it('returns nulls for an unparseable key', function () {
        expect($this->verifier->fingerprints('not a key'))->toBe([null, null]);
    });

    describe('mode off', function () {
        it('accepts any key', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, ['mode' => 'off']);
        })->throwsNoExceptions();

        it('is the default when no mode is given', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, []);
        })->throwsNoExceptions();
    });

    describe('mode fingerprints', function () {
        it('accepts a matching SHA256 pin', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, [
                'mode' => 'fingerprints',
                'fingerprints' => ['example.test' => WTS_SHA256],
            ]);
        })->throwsNoExceptions();

        it('accepts a matching MD5 pin', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, [
                'mode' => 'fingerprints',
                'fingerprints' => ['example.test' => WTS_MD5],
            ]);
        })->throwsNoExceptions();

        it('rejects a wrong fingerprint', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, [
                'mode' => 'fingerprints',
                'fingerprints' => ['example.test' => 'SHA256:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'],
            ]);
        })->throws(HostKeyVerificationException::class);

        it('rejects a host that is not pinned at all', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'unpinned.test', 22, [
                'mode' => 'fingerprints',
                'fingerprints' => ['example.test' => WTS_SHA256],
            ]);
        })->throws(HostKeyVerificationException::class);

        it('prefers a host:port pin and honors it', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'example.test', 2222, [
                'mode' => 'fingerprints',
                'fingerprints' => ['example.test:2222' => WTS_SHA256],
            ]);
        })->throwsNoExceptions();

        it('accepts any of several pinned fingerprints for a host', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, [
                'mode' => 'fingerprints',
                'fingerprints' => ['example.test' => ['SHA256:wrongwrongwrong', WTS_SHA256]],
            ]);
        })->throwsNoExceptions();
    });

    describe('mode known_hosts', function () {
        it('accepts a matching plaintext entry', function () {
            $path = tempnam(sys_get_temp_dir(), 'wts-kh');
            file_put_contents($path, 'example.test '.WTS_HOST_KEY."\n");

            try {
                $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, [
                    'mode' => 'known_hosts',
                    'known_hosts_path' => $path,
                ]);
            } finally {
                @unlink($path);
            }
        })->throwsNoExceptions();

        it('accepts a matching hashed entry on a non-standard port', function () {
            $path = tempnam(sys_get_temp_dir(), 'wts-kh');
            // Hashed [example.test]:2222 entry generated by `ssh-keygen -H`.
            file_put_contents($path, '|1|XR4rllSgD7GZKutbco+T+RadPwo=|YpMkPOG9Y90E+Q7lXvmwPB9GnXY= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN3+5ljw+B4IQLbmebVHtrrGv12iu4/ZPUZH5T/+yNB1'."\n");

            try {
                $this->verifier->verify(WTS_HOST_KEY, 'example.test', 2222, [
                    'mode' => 'known_hosts',
                    'known_hosts_path' => $path,
                ]);
            } finally {
                @unlink($path);
            }
        })->throwsNoExceptions();

        it('rejects a host absent from the file', function () {
            $path = tempnam(sys_get_temp_dir(), 'wts-kh');
            file_put_contents($path, 'other.test '.WTS_HOST_KEY."\n");

            try {
                expect(fn () => $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, [
                    'mode' => 'known_hosts',
                    'known_hosts_path' => $path,
                ]))->toThrow(HostKeyVerificationException::class);
            } finally {
                @unlink($path);
            }
        });

        it('rejects when the key differs for a known host', function () {
            $path = tempnam(sys_get_temp_dir(), 'wts-kh');
            file_put_contents($path, 'example.test ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'."\n");

            try {
                expect(fn () => $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, [
                    'mode' => 'known_hosts',
                    'known_hosts_path' => $path,
                ]))->toThrow(HostKeyVerificationException::class);
            } finally {
                @unlink($path);
            }
        });

        it('throws when the known_hosts path is missing', function () {
            $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, [
                'mode' => 'known_hosts',
                'known_hosts_path' => '/no/such/file',
            ]);
        })->throws(HostKeyVerificationException::class);
    });

    it('throws on an unknown mode', function () {
        $this->verifier->verify(WTS_HOST_KEY, 'example.test', 22, ['mode' => 'bogus']);
    })->throws(HostKeyVerificationException::class);
});
